### ISSUE TITLE
光标残影透明度

### ISSUE THREAD

**Issue by shynur** [lynnux/pop-select#2]
请问能给光标的拖影加一个alpha透明度的功能吗？

**Comment by lynnux** [comment]
![test](https://github.com/lynnux/pop-select/assets/367894/c5bf671e-532a-4fb5-8650-24b1d28d60a8)
简单试了下目前暂时不行，因为有个顶层窗口是黑色已经被设置为透明色了，如果加上alpha那个顶层窗口也变透明就显示出来了，如图所示。
有个变通的方法：可以尝试设置r g b 为深一点的颜色试试。

**Comment by shynur** [comment]
> 可以尝试设置r g b 为深一点的颜色试试。

我随便试了 0,0,0  , 好像全部是0的时候没有拖影了

**Comment by lynnux** [comment]
0.0.0即黑色是透明色，这个显示光标残影的原理创建一个全屏顶层窗口，并把其背景色设置为黑色，然后在这个窗口里画其它颜色的不规则四边形。这样光标的位置就是屏幕坐标，恰好emacs也提供了光标屏幕坐标的方法，这样的好处是不需要考虑emacs窗口位置相对坐标换算等麻烦的事，这应该也是区别于`holo-layer`的实现之一（没有细看它的实现，说法可能有误）。
所以，光标残影就不能设置为黑色啦，还有设置后重启才有效果。

**Comment by shynur** [comment]
> 可以尝试设置r g b 为深一点的颜色试试。

试了下, 效果不错.

我写了一段根据背景色修改残影颜色的明暗程度的elisp代码 (它只会在第一个命令被调用前运行), 可以加到ReadMe里面吗?

**Comment by lynnux** [comment]
> > 可以尝试设置r g b 为深一点的颜色试试。
> 
> 试了下, 效果不错.
> 
> 我写了一段根据背景色修改残影颜色的明暗程度的elisp代码 (它只会在第一个命令被调用前运行), 可以加到ReadMe里面吗?

可以的，已合并

**Comment by lynnux** [comment]
不过你的代码我测试没有效果，而且有点太多了，不利于调试，都加到ReadMe里供参考吧。

**Comment by shynur** [comment]
晚上我再试一下。这个我昨天测了几次应该是可以的。具体来说就是把第一节的加载代码和最后一节的光标代码放在一起，写到init里，然后重启。

**Comment by shynur** [comment]
知道问题出在哪儿了.

`-Q` 启动后光标是黑色的,

```
(color-lighten-name "black" 1)  ; => black
```

比 `黑色` 明亮 1% 的还是黑色, 这个时候残影是透明的, 显示不出来.

我打个补丁回避掉这种情况.
